#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""组会纪要模板生成+待办追踪"""
import os, sys
from datetime import datetime

def get_input(prompt, default=""):
    val = input(f"{prompt} [{default}]: ").strip()
    return val if val else default

def generate_meeting_minutes(meeting_info_file=None, output_file=None, template_type="standard"):
    """生成组会纪要

    可以从文件读取会议信息，或交互式输入
    """
    meeting = {
        "title": "",
        "date": datetime.now().strftime("%Y-%m-%d"),
        "time": "",
        "location": "",
        "presenter": "",
        "recorder": "",
        "attendees": "",
        "agenda": "",
        "discussion": "",
        "decisions": "",
        "action_items": "",
    }

    if meeting_info_file and os.path.exists(meeting_info_file):
        # 从文件读取 (key: value格式 或 Markdown)
        with open(meeting_info_file, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if ':' in line and not line.startswith('#'):
                    key, val = line.split(':', 1)
                    key = key.strip().lower().replace(' ', '_')
                    if key in meeting:
                        meeting[key] = val.strip()

    # 交互式补充缺失信息
    if not meeting["title"]:
        meeting["title"] = get_input("会议主题", f"组会-{meeting['date']}")
    if not meeting["presenter"]:
        meeting["presenter"] = get_input("主讲人", "")
    if not meeting["attendees"]:
        meeting["attendees"] = get_input("参会人员", "")
    if not meeting["agenda"]:
        meeting["agenda"] = get_input("议程概要", "待补充")
    if not meeting["discussion"]:
        meeting["discussion"] = get_input("讨论内容", "待补充")
    if not meeting["decisions"]:
        meeting["decisions"] = get_input("决议", "待补充")
    if not meeting["action_items"]:
        meeting["action_items"] = get_input("待办事项(分号分隔)", "待补充")

    # 解析待办事项
    action_list = [a.strip() for a in meeting["action_items"].split(';') if a.strip() and a.strip() != '待补充']

    # 生成纪要
    out_path = output_file or f"meeting_{meeting['date']}.md"

    with open(out_path, 'w', encoding='utf-8') as out:
        out.write(f"# {meeting['title']}\n\n")
        out.write(f"| 项目 | 内容 |\n|------|------|\n")
        out.write(f"| 日期 | {meeting['date']} |\n")
        out.write(f"| 时间 | {meeting['time'] or '待定'} |\n")
        out.write(f"| 地点 | {meeting['location'] or '待定'} |\n")
        out.write(f"| 主讲 | {meeting['presenter']} |\n")
        out.write(f"| 记录 | {meeting['recorder']} |\n")
        out.write(f"| 参会 | {meeting['attendees']} |\n\n")

        out.write(f"## 议程\n{meeting['agenda']}\n\n")
        out.write(f"## 讨论内容\n{meeting['discussion']}\n\n")
        out.write(f"## 决议\n{meeting['decisions']}\n\n")

        if action_list:
            out.write(f"## 待办事项\n")
            for i, action in enumerate(action_list, 1):
                out.write(f"- [ ] {action}\n")
            out.write("\n")
        else:
            out.write(f"## 待办事项\n- [ ] 待补充\n\n")

        out.write(f"---\n*Generated by lab-meeting-minute-generator on {datetime.now().strftime('%Y-%m-%d %H:%M')}*\n")

    print(f"Meeting minutes generated")
    print(f"  Title: {meeting['title']}")
    print(f"  Date: {meeting['date']}")
    print(f"  Action items: {len(action_list)}")
    print(f"  Output: {out_path}")

def main():
    print("=" * 60)
    print("  组会纪要模板生成+待办追踪")
    print("=" * 60)
    info_file = get_input("会议信息文件路径(留空=交互输入)", "")
    output = get_input("输出文件路径", "")
    generate_meeting_minutes(info_file or None, output or None)

if __name__ == "__main__":
    main()
