#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
============================================================
  r-script-template-generator
  R脚本模板生成工具
============================================================
"""

def get_input(prompt, default="", dtype=str):
    val = input(prompt + (" [" + str(default) + "]" if default else "") + ": ")
    if not val.strip():
        return default
    return dtype(val)

def generate_r_template(script_name, output="script_template.R"):
    """生成R脚本模板"""
    template = '''#!/usr/bin/env Rscript
# -*- coding: utf-8 -*-
# {title}
# Generated by r-script-template-generator

# 加载必要的包
# install.packages(c("ggplot2", "dplyr"))
library(ggplot2)
library(dplyr)

# 读取数据
# data <- read.csv("data.csv", sep=",", header=TRUE)

# 数据分析
# result <- data %>%
#   group_by(group) %>%
#   summarise(mean = mean(value), sd = sd(value))

# 可视化
# ggplot(result, aes(x=group, y=mean)) +
#   geom_bar(stat="identity") +
#   theme_minimal()

# 保存结果
# ggsave("plot.png", width=8, height=6, dpi=300)
# write.csv(result, "result.csv", row.names=FALSE)

cat("Analysis completed!\\n")
'''.format(title=script_name)
    
    with open(output, 'w') as f:
        f.write(template)
    
    print(f"R脚本模板已保存: {output}")

def main():
    print("\n" + "=" * 60)
    print("  R脚本模板生成工具")
    print("=" * 60)
    
    script_name = get_input("\n脚本名称", "my_analysis", str)
    output = get_input("输出R文件", "script_template.R", str)
    
    generate_r_template(script_name, output)
    print("\n完成!")

if __name__ == "__main__":
    main()
