#!/usr/bin/env python3
"""Circos plot data preparation + configuration generation"""

import os
import sys


def get_input(prompt, default="", dtype=str):
    val = input(prompt + (" [" + str(default) + "]" if default else "") + ": ")
    if not val.strip():
        return default
    return dtype(val)


def prepare_circos_data(karyotype_file, link_files, output_dir, highlight_file=None):
    """Prepare Circos input files from genomic data.

    Args:
        karyotype_file: Tab-delimited file with chr, label, start, end, color
        link_files: Comma-separated list of link BEDPE files
        output_dir: Output directory for Circos config and data files
        highlight_file: Optional BED file for highlight regions
    """
    os.makedirs(output_dir, exist_ok=True)

    # Parse karyotype
    chromosomes = []
    with open(karyotype_file) as f:
        for line in f:
            if line.startswith("#") or not line.strip():
                continue
            fields = line.strip().split("\t")
            if len(fields) >= 4:
                chrom = fields[0]
                label = fields[1] if len(fields) > 1 else chrom
                start = int(fields[2]) if len(fields) > 2 else 0
                end = int(fields[3]) if len(fields) > 3 else 0
                color = fields[4] if len(fields) > 4 else "chr" + chrom
                chromosomes.append((chrom, label, start, end, color))

    if not chromosomes:
        print("[ERROR] No chromosomes found in karyotype file")
        sys.exit(1)

    # Write karyotype file for Circos
    karyotype_out = os.path.join(output_dir, "karyotype.txt")
    with open(karyotype_out, "w") as out:
        for chrom, label, start, end, color in chromosomes:
            out.write(f"chr - {label} {chrom} {start} {end} {color}\n")

    # Process link files
    total_links = 0
    for i, link_file in enumerate(link_files):
        if not os.path.exists(link_file):
            print(f"[WARN] Link file not found: {link_file}, skipping")
            continue
        link_out = os.path.join(output_dir, f"links_{i}.txt")
        count = 0
        with open(link_file) as fin, open(link_out, "w") as fout:
            for line in fin:
                if line.startswith("#") or not line.strip():
                    continue
                fields = line.strip().split("\t")
                if len(fields) >= 6:
                    c1, s1, e1 = fields[0], int(fields[1]), int(fields[2])
                    c2, s2, e2 = fields[3], int(fields[4]), int(fields[5])
                    fout.write(f"{c1} {s1} {e1} {c2} {s2} {e2}\n")
                    count += 1
        total_links += count
        print(f"[INFO] Links file {i}: {count} links from {os.path.basename(link_file)}")

    # Process highlights
    highlight_count = 0
    if highlight_file and os.path.exists(highlight_file):
        highlight_out = os.path.join(output_dir, "highlights.txt")
        with open(highlight_file) as fin, open(highlight_out, "w") as fout:
            for line in fin:
                if line.startswith("#") or line.startswith("track") or not line.strip():
                    continue
                fields = line.strip().split("\t")
                if len(fields) >= 3:
                    chrom, start, end = fields[0], int(fields[1]), int(fields[2])
                    color = fields[3] if len(fields) > 3 else "red"
                    fout.write(f"{chrom} {start} {end} fill_color={color}\n")
                    highlight_count += 1

    # Generate Circos configuration file
    config_out = os.path.join(output_dir, "circos.conf")
    with open(config_out, "w") as out:
        out.write("# Circos configuration generated by circos_plot_builder\n\n")
        out.write("karyotype = karyotype.txt\n\n")
        out.write("<ideogram>\n")
        out.write("  show_label = yes\n")
        out.write("  label_font = default\n")
        out.write("  label_radius = dims(ideogram,radius) + 20p\n")
        out.write("  spacing = 2u\n")
        out.write("  thickness = 15p\n")
        out.write("  fill = yes\n")
        out.write("  fill_color = blues-9-seq-1\n")
        out.write("  radius = 0.85r\n")
        out.write("</ideogram>\n\n")

        for i in range(len(link_files)):
            if os.path.exists(os.path.join(output_dir, f"links_{i}.txt")):
                out.write(f"<link link{i}>\n")
                out.write(f"  file = links_{i}.txt\n")
                out.write("  radius = 0.75r\n")
                out.write("  bezier_radius = 0.1r\n")
                out.write("  color = black_a5\n")
                out.write("  thickness = 1\n")
                out.write(f"</link>\n\n")

        if highlight_count > 0:
            out.write("<highlight>\n")
            out.write("  file = highlights.txt\n")
            out.write("  r0 = 0.85r\n")
            out.write("  r1 = 0.90r\n")
            out.write("</highlight>\n\n")

        out.write("<image>\n")
        out.write("  dir = .\n")
        out.write("  file = circos.png\n")
        out.write("  radius* = 1500p\n")
        out.write("  background = white\n")
        out.write("</image>\n\n")
        out.write("<<etc/colors_fonts_patterns.conf>>\n")
        out.write("<<etc/housekeeping.conf>>\n")

    return {
        "chromosomes": len(chromosomes),
        "links": total_links,
        "highlights": highlight_count,
        "config_file": config_out,
    }


def main():
    print("=" * 60)
    print("  Circos Plot Data Preparation + Config Generation")
    print("=" * 60)
    print()

    karyotype_file = get_input("Karyotype file (chr,label,start,end,color)", "karyotype.txt")
    link_input = get_input("Link BEDPE files (comma-separated)", "links.bedpe")
    output_dir = get_input("Output directory", "circos_output")
    highlight_file = get_input("Highlight BED file (empty=none)", "")

    if not os.path.exists(karyotype_file):
        print(f"[ERROR] Karyotype file not found: {karyotype_file}")
        sys.exit(1)

    link_files = [f.strip() for f in link_input.split(",") if f.strip()]

    stats = prepare_circos_data(
        karyotype_file, link_files, output_dir,
        highlight_file if highlight_file else None,
    )

    print()
    print("=" * 60)
    print("  RESULTS SUMMARY")
    print("=" * 60)
    print(f"  Chromosomes:      {stats['chromosomes']}")
    print(f"  Links:            {stats['links']}")
    print(f"  Highlights:       {stats['highlights']}")
    print(f"  Config file:      {stats['config_file']}")
    print(f"  Output dir:       {output_dir}")
    print("=" * 60)
    print()
    print("[Done] Circos data preparation completed successfully!")
    print("[INFO] Run: circos -conf " + stats['config_file'])


if __name__ == "__main__":
    main()
