#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
============================================================
  plot-template-saver
  matplotlib图表模板保存工具
============================================================"""

def get_input(prompt, default="", dtype=str):
    val = input(prompt + (" [" + str(default) + "]" if default else "") + ": ")
    if not val.strip():
        return default
    return dtype(val)

def save_plot_template(template_name, output="plot_template.py"):
    """保存matplotlib图表模板"""
    template_code = '''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
{title} - Matplotlib Plot Template
Generated by plot-template-saver
"""

import matplotlib
matplotlib.use('Agg')  # For non-interactive backend
import matplotlib.pyplot as plt
import numpy as np

def create_plot():
    """Create the plot figure"""
    fig, ax = plt.subplots(figsize=(8, 6))
    
    # Add your plotting code here
    # Example:
    # x = np.linspace(0, 10, 100)
    # y = np.sin(x)
    # ax.plot(x, y)
    
    ax.set_xlabel('X Label')
    ax.set_ylabel('Y Label')
    ax.set_title('{title}')
    ax.grid(True, alpha=0.3)
    
    plt.tight_layout()
    return fig, ax

if __name__ == "__main__":
    fig, ax = create_plot()
    plt.savefig('{output}.png', dpi=300)
    plt.close()
    print("Plot saved to {output}.png")
'''.format(title=template_name, output=template_name.replace(' ', '_'))
    
    with open(output, 'w') as f:
        f.write(template_code)
    
    print(f"模板已保存: {output}")

def main():
    print("\n" + "=" * 60)
    print("  Matplotlib图表模板保存工具")
    print("=" * 60)
    
    template_name = get_input("\n模板名称", "my_plot", str)
    output = get_input("输出Python文件", "plot_template.py", str)
    
    save_plot_template(template_name, output)
    print("\n完成!")

if __name__ == "__main__":
    main()
